# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.21"
  amd64: "ghcr.io/home-assistant/amd64-base:3.21"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: TooGoodToGo watcher"
  org.opencontainers.image.description: "Add-on for monitoring your favorite TooGoodToGo businesses."
  org.opencontainers.image.source: "https://github.com/marklagendijk/ha-toogoodtogo-watcher"
  org.opencontainers.image.licenses: "MIT License"
args:
  TEMPIO_VERSION: "2021.09.0"
