# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TooGoodToGo watcher
version: "0.6.15"
slug: toogoodtogo-watcher
description: Add-on for monitoring your favorite TooGoodToGo businesses.
url: "https://github.com/marklagendijk/ha-toogoodtogo-watcher/tree/main/toogoodtogo-watcher"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
options:
  config: |
    {
      "api": {
        "credentials": {
          "email": "Email of your TooGoodToGo account."
        }
      },
      "notifications": {
        "telegram": {
          "botToken": "See README"
        }
      }
    }
schema:
  config: "str"
image: "ghcr.io/marklagendijk/{arch}-toogoodtogo-watcher"
