# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: TooGoodToGo watcher
version: "1.0.0"
slug: node-toogoodtogo-watcher
description: Add-on for monitoring your favorite TooGoodToGo businesses.
url: "https://github.com/marklagendijk/ha-toogoodtogo-watcher/tree/main/toogoodtogo-watcher"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: False
image: "ghcr.io/marklagendijk/{arch}-toogoodtogo-watcher"
